version: '3.3'

services:
  web:
    build: ./site
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./site/:/usr/src/site/
    ports:
      - 8000:8000
    env_file:
      - ./.env